### ISSUE TITLE
生成语句的问题

### ISSUE THREAD

**Issue by zhiyuanjiang** [Alic-yuan/nlp-beginner-finish#8]
大佬你好，我想问一下你使用过邱老师提供的那个数据集吗？我使用那个数据集后，随机生成句子的时候总是生成像<END><PAD>这种字符，请问你能给我提供一点点建议吗，非常感谢。

**Comment by Alic-yuan** [comment]
我没有用过邱老师的那个数据集哈，生成错误字符多半还是数据集的问题，可以找些质量更好的数据集试下。

**Comment by zhiyuanjiang** [comment]
好的，谢谢大佬
